---
logging:
  file: logs/mod-spine-o-matic.log
  level:
    org:
      tamu.modspineomatic: INFO
      hibernate: INFO
      springframework:
        security: INFO
        web: INFO

---
server:
  port: 9000

---
okapi:
  url: https://folio-okapi-q3.library.tamu.edu
  credentials:
    username: tamu_admin
    password:
  tenant: tamu

---
spring:

  thymeleaf:
      suffix: .xml
      templateMode: XML
      cacheable: false

---
call-number-types:
  - name: Dewey
    type: 1
  - name: Library of Congress
    type: 0
  - name: National Library of Medicine
    type: 0
  - name: Superintendent of Documents
    type: 3
  - name: No information provided
    type: 4
  - name: Other scheme
    type: 4
  - name: Shelved separately
    type: 4
  - name: Shelving control number
    type: 4
  - name: Source specified in subfield $2
    type: 4
  - name: Title
    type: 4
