---
logging:
  file: logs/mod-spine-o-matic.log
  level:
    org:
      tamu.modspineomatic: INFO
      hibernate: INFO
      springframework:
        security: INFO
        web: INFO

---
server:
  port: 9000

---
okapi:
  url: https://folio-okapi-q3.library.tamu.edu
  credentials:
    username: tamu_admin
    password: admin
  tenant: tamu

---
spring:

  thymeleaf:
      suffix: .xml
      templateMode: XML
      cacheable: false
