#%RAML 1.0

title: Spine
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Spine API
    content: This documents the API calls that can be made to get spine labels

/spine-label:
  get:
    description: Get spine label by ID.
    queryParameters:
      identifier:
        description: ID
        type: string
        required: true
    responses:
      200:
        description: OK
        body:
          application/json: